
version: '3.1'

services:

  rproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./docker/rpoxy:/data
      - ./docker/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - backend
  
  web:
    build: ./web
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo 
    environment:
      HTTP_PORT: :3000
      MONGO_USER: logger_fitenss
      MONGO_USER_PASS: lsPass
      MONGO_URL: mongo
      MONGO_PORT: 27017
      MONGO_NAME: logger_fitness_db
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./docker/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
       - ./docker/docker-data/mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #ports:
      #- 27017:27017
    command: [--auth]

  mongo-express:
    image: mongo-express
    restart: always
    #ports:
      #- 8081:8081
    depends_on:
      - mongo 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
