
version: '3.9'

services:

  rproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./docker/volumes/rproxy:/data
      - ./docker/volumes/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo 
    environment:
      HTTP_PORT: :3000
      MONGO_USER: logger_fitenss
      MONGO_USER_PASS: lsPass
      MONGO_URL: mongo
      MONGO_PORT: 27017
      MONGO_NAME: logger_fitness_db
    #ports:
      #- "3000:3000"

networks:
  default:
    external:
      name: logger_fitness_network
