version: '3.1'

services:
  
  database:
      image: 'postgres:latest'
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
        POSTGRES_DB: fitness_logger_db # The PostgreSQL default database (automatically created at first launch)

      # volume for persistent database betweein multiple docker-compose runs
      volumes:
        - ./docker/volumes:/var/lib/postgresql/data/
